### ISSUE TITLE
Failed to load resource error in SWF library loading Examples

### ISSUE THREAD

**Issue by Gamezpedia** [openfl/openfl-samples-es6#1]
After updating from 7.0.0 to 7.1.0 

**UsingSWFAssets** sample is giving :

![image](https://user-images.githubusercontent.com/1169093/36032560-3bd84656-0dd0-11e8-84e0-2764d08db54b.png)

Same with the **NayanCat** :

![image](https://user-images.githubusercontent.com/1169093/36032908-45de4c94-0dd1-11e8-90d4-abe71daced57.png)

Some warnings which are always there when creating a project in ES6, ES5 or TypeScript (I tested these three)

![image](https://user-images.githubusercontent.com/1169093/36033454-eef8b7e6-0dd2-11e8-846d-d1d7f7b95fa4.png)

**Comment by jgranick** [comment]
Fixed in https://github.com/openfl/openfl/commit/1e47622ade444d3702f094b8ab302f0d246fd4de and https://github.com/openfl/lime/commit/18c7bf68461eccbc34aa9f0298ab78038b57c130, will release 7.1.1 soon with this fix, thank you :smile:

**Comment by jgranick** [comment]
Released! 😎
